GET https://bwabank.my.id/api/operator_cards
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYndhYmFuay5teS5pZFwvYXBpXC9sb2dpbiIsImlhdCI6MTY4MzM2MDA5NCwiZXhwIjoxNjgzMzYzNjk0LCJuYmYiOjE2ODMzNjAwOTQsImp0aSI6Im1vM2dDbFRwZTR4Z2M1Z0YiLCJzdWIiOjQxOCwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.72noO3aOd3GJQPadoNSE3Ba9Y9f8xeuySLhxJPAjlUg